# Generated by Django 6.0 on 2026-01-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('HR', 'HR'), ('EMPLOYEE', 'Employee')], db_index=True, default='EMPLOYEE', max_length=20),
        ),
    ]
