# Generated by Django 6.0 on 2026-01-04 07:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='scores',
            new_name='probs',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='event',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='model_version',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='primary_emotion',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='source',
        ),
        migrations.AddField(
            model_name='feedback',
            name='emotion',
            field=models.CharField(default=django.utils.timezone.now, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='event_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='face_box',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='top3',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='department',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
