# Generated by Django 6.0 on 2026-01-04 15:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_rename_scores_feedback_probs_remove_feedback_event_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='event_id',
        ),
        migrations.AddField(
            model_name='feedback',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='feedback.event'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks', to='feedback.department'),
        ),
        migrations.AddField(
            model_name='department',
            name='company',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='feedback.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='company',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='feedback.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks', to='feedback.company'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('company', 'name')},
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['created_at'], name='feedback_fe_created_84c297_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['emotion'], name='feedback_fe_emotion_4e77f0_idx'),
        ),
    ]
