# Generated by Django 6.0.1 on 2026-01-31 19:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_company_remove_feedback_event_id_feedback_event_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='face_box',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='probs',
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
    ]
