# Generated by Django 6.0.1 on 2026-01-31 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_remove_feedback_confidence_remove_feedback_face_box_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ends_at',
            field=models.DateTimeField(),
        ),
    ]
